package com.main.enums;

public enum AllPopulations
{
    HISPANIC, WHITE, BLACK, ASIAN, NATIVE_AMERICAN, NATIVE_HAWAIIAN, DEMOCRAT, REPUBLICAN, LIBERTARIAN,
    INDEPENDENT, TOTAL, VOTING_AGE, CITIZEN_VOTING_AGE
}