package com.main.enums;

public enum Measures
{
    EQUAL_POPULATION, DEVIATION_ENACTED, DEVIATION_ENACTED_GEO, DEVIATION_ENACTED_POP, DEVIATION_AVERAGE,
    SPLIT_COUNTIES, COMPACTNESS, POLITICAL_FAIRNESS, OBJECTIVE_SCORE
}